name: Docker Image CI

on: 
  workflow_dispatch:
    inputs:
      command:
        required: true
        description: 'command to execute'     
        default: 'docker-compose up -d' 
        type: choice
        options:
        - docker-compose up -d
        - docker-compose up -d --build
jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: ${{ inputs.command }}
